var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(storefront)/tai-khoan/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__094y_nf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0r5mtca._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_1oy1nwh.js")
R.c("server/chunks/ssr/node_modules_next_dist_1ujwiy7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jq_uwy._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/[root-of-the-server]__128qlel._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1pkq46l._.js")
R.c("server/chunks/ssr/_0v8gfov._.js")
R.c("server/chunks/ssr/_05heety._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(storefront)_tai-khoan_page_actions_0hdbku9.js")
R.m(499627)
module.exports=R.m(499627).exports
