// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/[[...segments]]" | "/admin/change-password" | "/blog" | "/blog/[slug]" | "/dai-ly" | "/gio-hang" | "/gioi-thieu" | "/kien-thuc" | "/kien-thuc/[slug]" | "/lien-he" | "/san-pham" | "/san-pham/[slug]" | "/tai-khoan" | "/test-upload-bo" | "/thanh-toan" | "/tu-van"
type AppRouteHandlerRoutes = "/api/[...slug]" | "/api/auth/[...nextauth]" | "/api/consultations" | "/api/contact" | "/api/dealers" | "/api/files/[key]" | "/api/graphql" | "/api/graphql-playground" | "/api/orders" | "/api/search" | "/api/upload"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin/[[...segments]]": { "segments"?: string[]; }
  "/admin/change-password": {}
  "/api/[...slug]": { "slug": string[]; }
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/consultations": {}
  "/api/contact": {}
  "/api/dealers": {}
  "/api/files/[key]": { "key": string; }
  "/api/graphql": {}
  "/api/graphql-playground": {}
  "/api/orders": {}
  "/api/search": {}
  "/api/upload": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/dai-ly": {}
  "/gio-hang": {}
  "/gioi-thieu": {}
  "/kien-thuc": {}
  "/kien-thuc/[slug]": { "slug": string; }
  "/lien-he": {}
  "/san-pham": {}
  "/san-pham/[slug]": { "slug": string; }
  "/tai-khoan": {}
  "/test-upload-bo": {}
  "/thanh-toan": {}
  "/tu-van": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
