// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(payload)/admin/[[...segments]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/[[...segments]]">> = Specific
  const handler = {} as typeof import("../../src/app/(payload)/admin/[[...segments]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(payload)/admin/change-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/change-password">> = Specific
  const handler = {} as typeof import("../../src/app/(payload)/admin/change-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(storefront)/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(storefront)/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(storefront)/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/(storefront)/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(storefront)/dai-ly/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dai-ly">> = Specific
  const handler = {} as typeof import("../../src/app/(storefront)/dai-ly/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(storefront)/gio-hang/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gio-hang">> = Specific
  const handler = {} as typeof import("../../src/app/(storefront)/gio-hang/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(storefront)/gioi-thieu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gioi-thieu">> = Specific
  const handler = {} as typeof import("../../src/app/(storefront)/gioi-thieu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(storefront)/kien-thuc/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kien-thuc/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(storefront)/kien-thuc/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(storefront)/kien-thuc/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kien-thuc">> = Specific
  const handler = {} as typeof import("../../src/app/(storefront)/kien-thuc/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(storefront)/lien-he/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lien-he">> = Specific
  const handler = {} as typeof import("../../src/app/(storefront)/lien-he/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(storefront)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(storefront)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(storefront)/san-pham/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/san-pham/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(storefront)/san-pham/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(storefront)/san-pham/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/san-pham">> = Specific
  const handler = {} as typeof import("../../src/app/(storefront)/san-pham/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(storefront)/tai-khoan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tai-khoan">> = Specific
  const handler = {} as typeof import("../../src/app/(storefront)/tai-khoan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(storefront)/test-upload-bo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-upload-bo">> = Specific
  const handler = {} as typeof import("../../src/app/(storefront)/test-upload-bo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(storefront)/thanh-toan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/thanh-toan">> = Specific
  const handler = {} as typeof import("../../src/app/(storefront)/thanh-toan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(storefront)/tu-van/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tu-van">> = Specific
  const handler = {} as typeof import("../../src/app/(storefront)/tu-van/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(payload)/api/[...slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[...slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(payload)/api/[...slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(payload)/api/graphql-playground/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graphql-playground">> = Specific
  const handler = {} as typeof import("../../src/app/(payload)/api/graphql-playground/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(payload)/api/graphql/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graphql">> = Specific
  const handler = {} as typeof import("../../src/app/(payload)/api/graphql/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/consultations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/consultations">> = Specific
  const handler = {} as typeof import("../../src/app/api/consultations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../src/app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dealers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dealers">> = Specific
  const handler = {} as typeof import("../../src/app/api/dealers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/files/[key]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/files/[key]">> = Specific
  const handler = {} as typeof import("../../src/app/api/files/[key]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(payload)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(payload)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(storefront)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(storefront)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
